system:
  base_dir: "/home/davidm/coding/GeometricReasoning"

model:
  name: "NeuroSAT"
  d: 96
  final_reducer: "mean"
  num_iters: 25

train:
  seed: 0
  num_epochs: 200
  lr: 1e-3
  weight_decay: 1e-10
  gradient_clip_val: 0.65
  scheduler: "linear"
  accelerator: "gpu"
  devices: 1
  save_checkpoints: true

data:
  data_path: "${system.base_dir}/temp/geo/geometry_problems_most_new.pickle" #geometry_problems_most_new.pickle
  batch_size: 64
  num_workers: 4
  max_size: 20
  max_constraints: 20
  valid_split: 0.9